### ISSUE TITLE
Remove 'auto-updater' option as it is not used by jobs_done

### ISSUE THREAD

**Issue by nicoddemus** [ESSS/jobs_done10#12]
One idea is to move that configuration to another file that we have on `root` already, for example `pyproject.toml`:

This:

```yaml
auto-updater:
  target-branch: "pseudo-master"
  jobs:
    - "*-develop-win64"
  reviewers:
    - "bruno"
    - "darci"
```

Becomes:

```toml
[tool.auto-updater]
target-branch = "pseudo-master"
jobs = ["*-develop-win64"]
reviewers = ["bruno", "darci"]
```

--- 

Quick script for reference:

```python
import yaml, toml
from pprint import pprint
from io import StringIO

x = """
auto-updater:
  target-branch: "pseudo-master"
  jobs:
    - "*-develop-win64"
  reviewers:
    - "bruno"
    - "darci"
"""

pprint(yaml.safe_load(StringIO(x)))

t = """
[tool.auto-updater]
target-branch = "pseudo-master"
jobs = ["*-develop-win64"]
reviewers = ["bruno", "darci"]
"""

pprint(toml.loads(t))

```

Output:

```python
# λ python fo-toml.py
{'auto-updater': {'jobs': ['*-develop-win64'],
                  'reviewers': ['bruno', 'darci'],
                  'target-branch': 'pseudo-master'}}
{'tool': {'auto-updater': {'jobs': ['*-develop-win64'],
                           'reviewers': ['bruno', 'darci'],
                           'target-branch': 'pseudo-master'}}}
```
